POST http://localhost:3001/api/notes 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MzNhZjdiMmJhMGRjYTkzYTljMjM0NTMiLCJpYXQiOjE2NjY1MjY0OTQsImV4cCI6MTY2NjUzMDA5NH0.r7ucBq0aKpU9gTUNMv_PlNMXUu9-dNbZxAQ3OZ60bu4

{
    "content": "note after adding tokenExtractor in app.js to all routes, Note created by mluukkai salainen",
    "important": true
}

###
GET http://localhost:3001/api/notes HTTP/1.1


###
GET http://localhost:3001/api/notes/jkgdjgk85585 HTTP/1.1


### 
DELETE http://localhost:3001/api/notes/6326dc1bd1e875af5f328601 HTTP/1.1



###
PUT http://localhost:3001/api/notes/6326cd87476c1b44ca6e8c2f HTTP/1.1
Content-Type: : application/json

{
    "content": "How to connect to mongoDB changed",
    "important": false
}